NAME = main
PDFDIR = ../../../pdf
TEXC = pdflatex

SUBJECT := $(shell basename `dirname $(CURDIR)`)
PRACTICE := $(notdir $(CURDIR))

all: pdf
pdf: $(NAME).pdf
$(NAME).pdf: $(NAME).tex
	$(TEXC) $(NAME)

install: $(PDFDIR)/$(SUBJECT)/$(PRACTICE).pdf
$(PDFDIR)/$(SUBJECT)/$(PRACTICE).pdf: $(NAME).pdf
	mkdir -p $(PDFDIR)/$(SUBJECT)/
	cp -u $(NAME).pdf $(PDFDIR)/$(SUBJECT)/$(PRACTICE).pdf

clean:
	rm -fv *.aux *.log *.fls *.fdb_latexmk

distclean: clean
	rm -fv $(NAME).pdf
